#!/usr/bin/env python3
"""Build the object reference.

Objects here means the things that are not sprites and not tiles: the transient
ancillae Link and the enemies create, the invisible overlords that spawn things,
the prize packs a cut bush or a dead enemy rolls on, and the liftable map cells.

Sources, all read rather than typed in:

  ancillae     the handlers in src/ancilla.c, whose names spell their own type id
  overlords    kOverlordFuncs in src/overlord.c
  prizes       kPrizeItems and kPrizeMasks in src/sprite.c
  liftables    kLiftableCells in src/debug_locate.c
  damage       kPlayerDamages and the bomb tables in src/sprite.c and src/ancilla.c
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FPS = 60.0


def bodies(text):
    out = {}

    for m in re.finditer(r"\n(?:static )?(?:void|int|bool) (\w+)\([^)]*\) \{", text):
        i = m.end()
        depth = 1

        while i < len(text) and depth:
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
            i += 1

        out[m.group(1)] = text[m.end():i]

    return out


def spaced(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)


def table(text, name, cast=lambda v: int(v, 0)):
    start = text.index(name)
    body = text[text.index("{", start) + 1:text.index("};", start)]
    return [cast(v.strip()) for v in body.replace("\n", " ").split(",") if v.strip()]


def main():
    anc_text = (ROOT / "src" / "ancilla.c").read_text()
    spr_text = (ROOT / "src" / "sprite.c").read_text()
    ovl_text = (ROOT / "src" / "overlord.c").read_text()
    main_text = (ROOT / "src" / "sprite_main.c").read_text()
    loc_text = (ROOT / "src" / "debug_locate.c").read_text()

    anc_fns = bodies(anc_text)
    sprite_names = {}

    for hexid, nm in re.findall(r"Sprite_([0-9A-Fa-f]{2})_(\w+)", main_text):
        sprite_names.setdefault(int(hexid, 16), nm)

    # Ancillae. The handler name carries the type, so position in the table is not trusted.
    ancillae = {}

    for m in re.finditer(r"void Ancilla([0-9A-Fa-f]{2})_(\w+)\(", anc_text):
        ancillae.setdefault(int(m.group(1), 16), m.group(2))

    damages = table(spr_text, "kPlayerDamages[30]")
    classes = [damages[i * 3:i * 3 + 3] for i in range(10)]
    bomb_link = table(anc_text, "kBomb_Dmg_ToLink[3]")
    bomb_delay = table(anc_text, "kBomb_Dmg_Delay[16]")
    prize_items = table(spr_text, "kPrizeItems[56]")
    prize_masks = table(spr_text, "kPrizeMasks[7]")

    print("# Object reference\n")
    print("The things that are neither sprites nor tiles. Sprites are in `enemy_combat.md`")
    print("and `boss_combat.md`, tile behaviour is in `ground_types.md`, and rooms are in")
    print("`dungeon_rooms.md`.\n")
    print("Generated by `tools/object_reference.py`. Timers are frame counts, and a frame")
    print("is about a sixtieth of a second.\n")

    print("## Ancillae\n")
    slots = re.search(r"kAncilla_Funcs\[(\d+)\]", anc_text).group(1)
    print(f"{len(ancillae)} named handlers filling {slots} slots in `src/ancilla.c`. The gap is")
    print("slots pointing at `Ancilla_Empty` or sharing another type's handler. An ancilla is")
    print("a transient object with no health and no sprite slot: a bomb, an arrow in")
    print("flight, a splash, a puff of smoke. Link's weapons are here, and so are the")
    print("effects enemies leave behind.\n")
    print("| Type | Name | Functions | Timers | Sounds | Spawns ancilla |")
    print("| --- | --- | --- | --- | --- | --- |")

    detail = []

    for t in sorted(ancillae):
        stem = ancillae[t]
        # "Bomb" must not swallow "Bombos", so the stem has to end at a word boundary, and a
        # function named for a different ancilla type never belongs to this one.
        stem_re = re.compile(re.escape(stem) + r"(?![a-z])")
        other = re.compile(r"^Ancilla([0-9A-Fa-f]{2})_")
        related = {}

        for n, b in anc_fns.items():
            m = other.match(n)

            if m and int(m.group(1), 16) != t:
                continue

            if n.startswith(f"Ancilla{t:02X}_") or stem_re.search(n):
                related[n] = b
        blob = "\n".join(related.values()) or anc_fns.get(f"Ancilla{t:02X}_{stem}", "")
        tm = sorted({int(v, 0) for v in re.findall(
            r"ancilla_(?:timer|aux_timer)\[\w+\]\s*=\s*(0x[0-9a-fA-F]+|\d+)", blob) if int(v, 0)})
        sfx = sorted({int(v, 0) for v in re.findall(
            r"sound_effect_\d\s*=\s*(0x[0-9a-fA-F]+|\d+)", blob)})
        adds = sorted({int(v, 0) for v in re.findall(
            r"AncillaAdd_\w+\((0x[0-9a-fA-F]+|\d+)", blob)})
        print(f"| `{t:02X}` | {spaced(stem)} | {len(related)} | "
              f"{len(tm) or '-'} | {', '.join('`%02X`' % s for s in sfx) or '-'} | "
              f"{', '.join('`%02X`' % a for a in adds) or '-'} |")
        detail.append((t, stem, related, blob, tm, sfx, adds))

    print("\n### Each ancilla\n")

    for t, stem, related, blob, tm, sfx, adds in detail:
        print(f"#### {spaced(stem)} `{t:02X}`\n")
        print(f"{len(related)} function{'' if len(related) == 1 else 's'}: "
              + ", ".join(f"`{n}`" for n in sorted(related)) + ".\n")

        if tm:
            print("Timers: " + ", ".join(f"{v} ({v / FPS:.2f}s)" for v in tm) + ".\n")

        if sfx:
            print("Sounds: " + ", ".join(f"`{s:02X}`" for s in sfx) + ".\n")

        if adds:
            print("Creates ancillae: " + ", ".join(
                f"`{a:02X}`" + (f" {spaced(ancillae[a])}" if a in ancillae else "")
                for a in adds) + ".\n")

    print("## Bomb damage\n")
    print("The bomb is the one ancilla with its own damage tables. What it costs Link")
    print("depends on his mail, and how long it stuns him depends on how close he was:\n")
    print("<sub><code>src/ancilla.c</code></sub>")
    print("```c")
    print("    static const uint8 kBomb_Dmg_Delay[16] = {32, 32, 32, 32, 32, 32, 24, 24, 24, 24, 24, 24, 16, 16, 16, 16};")
    print("    static const uint8 kBomb_Dmg_ToLink[3] = {8, 4, 2};")
    print("```\n")
    print(f"So {bomb_link[0]}, {bomb_link[1]} and {bomb_link[2]} against green, blue and red")
    print("mail, which is one heart down to a quarter. The stun runs from")
    print(f"{bomb_delay[0]} frames ({bomb_delay[0] / FPS:.2f}s) at the centre to")
    print(f"{bomb_delay[-1]} frames ({bomb_delay[-1] / FPS:.2f}s) at the edge, in three bands.\n")

    print("## How a weapon hurts an enemy\n")
    print("Contact damage to Link is one table. Damage the other way is two, and the pair")
    print("is why a given weapon does nothing to some enemies:\n")
    print("<sub><code>src/sprite.c</code></sub>")
    print("```c")
    print("  uint8 dmg = kEnemyDamages[damage_type_determiner * 8 | enemy_damage_data[sprite_type[k] * 16 | damage_type_determiner]];")
    print("```\n")
    print("`damage_type_determiner` is the weapon. `enemy_damage_data` is a 16 entry row per")
    print("sprite type saying how that enemy reacts to each weapon, and `kEnemyDamages` turns")
    print("the reaction into a number. A row entry of zero means immune, which is how")
    print("Mothula ignores the best sword until the bug fix patches its row.\n")

    print("## Prize packs\n")
    print("What a cut bush, a lifted rock or a dead enemy leaves behind. Seven packs of")
    print("eight, rolled on at the moment the thing is destroyed:\n")
    print("| Pack | Always drops | Contents |")
    print("| --- | --- | --- |")

    for pack in range(7):
        row = prize_items[pack * 8:pack * 8 + 8]
        always = "yes" if prize_masks[pack] == 0 else "no"
        print(f"| {pack} | {always} | " + " ".join(f"`{v:02X}`" for v in row) + " |")

    print()
    print("The mask decides whether the roll can come up empty:\n")
    print("<sub><code>src/sprite.c</code></sub>")
    print("```c")
    print("      if (!(GetRandomNumber() & kPrizeMasks[prize])) {")
    print("```\n")
    print("A mask of 1 keeps the low bit of a random number, so those packs drop about half")
    print("the time. Pack 3 has a mask of 0, so it always drops.\n")
    print("Only three of the prize types have a handler of their own:\n")

    for t in sorted({v for v in prize_items}):
        nm = sprite_names.get(t)
        if nm:
            print(f"- `{t:02X}` {spaced(nm)}")

    print()
    print("The rest share `Sprite_D9_GreenRupee` as their handler, with the type deciding")
    print("the graphic and the effect, so the source does not name them individually.\n")
    print("The bee is not in these packs. It is sprite `79`, with its own handler")
    print("`Sprite_79_Bee`, and a second form `B2` used once Link has caught one.\n")

    print("## Overlords\n")
    ovl = re.search(r"kOverlordFuncs\[(\d+)\]", ovl_text)
    names = re.findall(r"&(Overlord_\w+|\w+)", ovl_text[ovl_text.index("kOverlordFuncs"):
                                                        ovl_text.index("};", ovl_text.index("kOverlordFuncs"))])
    print(f"{ovl.group(1)} handlers in `src/overlord.c`. An overlord has no body. It sits in a")
    print("room or screen and makes things happen, usually spawning sprites on a timer.\n")

    for n in names:
        print(f"- `{n}`")

    print()
    print("Overlords share the sprite tables with real sprites. In the overworld data an")
    print("entry with an x of `E0` or more is an overlord, and in the dungeon tables a type")
    print("of `F4` or higher is one.\n")

    print("## Liftable map cells\n")
    print("Bushes, stones and rock piles are not objects or sprites. They are map16 cells")
    print("that `Overworld_HandleLiftableTiles` acts on, listed in `src/debug_locate.c`:\n")
    print("| Cell | What | Needs gloves |")
    print("| --- | --- | --- |")

    for cell, what, gloves in re.findall(
            r"\{(0x[0-9a-fA-F]+),\s*\"([^\"]+)\",\s*(true|false)\}", loc_text):
        print(f"| `{int(cell, 0):03X}` | {what} | {'yes' if gloves == 'true' else 'no'} |")

    print()
    print("Lifting one rolls on a prize pack, which is where a bush drops a heart or a")
    print("rupee. A cell whose class needs more gloves than Link has is grabbed rather than")
    print("lifted, so the same button does two different things.\n")

    print("## What is not here\n")
    print("Inventory items and the abilities they grant. Those are not a table: each item")
    print("is a branch in the player code, and turning them into a list means reading those")
    print("branches rather than reading data.\n")
    print("Keys and the doors they open. A door's state lives in the room header and the")
    print("save file, not in an object, and the association is made when the room loads.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
